/**
 * @fileoverview gRPC-Web generated client stub for AuthService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.2
// source: AuthService.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as AuthService_pb from './AuthService_pb'; // proto import: "AuthService.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/AuthService.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    AuthService_pb.LoginRequest,
    AuthService_pb.LoginResponse,
    (request: AuthService_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    AuthService_pb.LoginResponse.deserializeBinary
  );

  login(
    request: AuthService_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<AuthService_pb.LoginResponse>;

  login(
    request: AuthService_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: AuthService_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<AuthService_pb.LoginResponse>;

  login(
    request: AuthService_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: AuthService_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AuthService.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AuthService.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/AuthService.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    AuthService_pb.RegisterRequest,
    AuthService_pb.RegisterResponse,
    (request: AuthService_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    AuthService_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: AuthService_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<AuthService_pb.RegisterResponse>;

  register(
    request: AuthService_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: AuthService_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<AuthService_pb.RegisterResponse>;

  register(
    request: AuthService_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: AuthService_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AuthService.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AuthService.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorRestorePassword = new grpcWeb.MethodDescriptor(
    '/AuthService.AuthService/RestorePassword',
    grpcWeb.MethodType.UNARY,
    AuthService_pb.RestorePasswordRequest,
    AuthService_pb.RestorePasswordResponse,
    (request: AuthService_pb.RestorePasswordRequest) => {
      return request.serializeBinary();
    },
    AuthService_pb.RestorePasswordResponse.deserializeBinary
  );

  restorePassword(
    request: AuthService_pb.RestorePasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<AuthService_pb.RestorePasswordResponse>;

  restorePassword(
    request: AuthService_pb.RestorePasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: AuthService_pb.RestorePasswordResponse) => void): grpcWeb.ClientReadableStream<AuthService_pb.RestorePasswordResponse>;

  restorePassword(
    request: AuthService_pb.RestorePasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: AuthService_pb.RestorePasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/AuthService.AuthService/RestorePassword',
        request,
        metadata || {},
        this.methodDescriptorRestorePassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/AuthService.AuthService/RestorePassword',
    request,
    metadata || {},
    this.methodDescriptorRestorePassword);
  }

}

